name: Final - Build/Push ACR + Deploy final-api

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: acrfinalsude.azurecr.io
  IMAGE_NAME: azure-final
  WEBAPP_NAME: final-api

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (AZURE_CREDENTIALS)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR (REGISTRY_*)
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login $ACR_LOGIN_SERVER -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          TAG=${{ github.sha }}
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$TAG .
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$TAG
          echo "IMAGE=$ACR_LOGIN_SERVER/$IMAGE_NAME:$TAG" >> $GITHUB_ENV

      - name: Deploy image to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          images: ${{ env.IMAGE }}
